name: download_data
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pandas=1.2.3
  - pip=20.3.3
  - scikit-learn=0.24.1
  - matplotlib==3.6.2
  - plotly==4.4.1
  - pillow=8.1.2
  - mlflow=2.2.2
  - pip:
      - wandb==0.10.21
      - omegaconf==2.0.6
      - matplotlib==3.6.2